// web3 is an Ethereum client library
const Web3 = require('web3');
const web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://127.0.0.1:7545'));

// This file is generated by the Solidity compiler to easily interact with
// the contract using the web3 library.
const loginAbi = require('./solidity/build/contracts/Login2.json').abi;
const LoginContract = new web3.eth.Contract(loginAbi);

module.exports = LoginContract;